name: ML Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v3

      # Step 2: Setup Python environment
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: PYTHONPATH=src pytest tests/

      # Step 5: Train the model
      - name: Train model
        run: |
          PYTHONPATH=src python src/train.py

      # Step 6: List model folder contents (debug)
      - name: List model directory contents
        run: ls -l model/

      # Step 7: Upload the trained model as an artifact
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: iris-model
          path: model/iris_model.pkl
